CREATE TABLE IF NOT EXISTS drug_processing (id INT(11) NOT NULL AUTO_INCREMENT, PRIMARY KEY(id));
ALTER TABLE drug_processing ADD IF NOT EXISTS coords LONGTEXT NOT NULL;
ALTER TABLE drug_processing ADD IF NOT EXISTS rotation DOUBLE NOT NULL;
ALTER TABLE drug_processing ADD IF NOT EXISTS type VARCHAR(100) NOT NULL;